# Template sensors
- platform: template
  sensors:
    home_recycling_types:
      value_template: >-
        {% set collections = state_attr("sensor.home_recycling", "collections") %}
          {% if collections is none or collections|length == 0 %}
            n.r
          {% else %}
            {{ collections|join(", ") }}
        {% endif %}
    home_recycling_date:
      value_template: >-
        {{ state_attr("sensor.home_recycling", "pickup_date") }}

