# Simulate TV cucina as switch (to expose on Alexa)
- platform: template
  switches:
    tv_cucina:
      value_template: "{{ not is_state('media_player.tv_cucina', 'unavailable') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.tv_cucina_power_on
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.tv_cucina_power_off

# Simulate TV sala as switch (to expose on Alexa)
- platform: template
  switches:
    tv_sala:
      value_template: "{{ is_state('media_player.samsung_tv', 'on') }}"
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.tv_sala_power_on
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.tv_sala_power_off

# Wake on LAN mbpm1
- platform: wake_on_lan
  name: wakeonl_mbpm1
  mac: !secret mac_mbpm1_wifi
